### PR TITLE
Resolve Issue 107

### PR DESCRIPTION
**Pull request by drothschild**
I was running jsPrettier, which formatted the code, which is why it looks like the entire files were rewritten.

### CODE REVIEW

**Comment by squanto** [comment]
Hi @drothschild , I'm just another dev looking over this. It may be easier to see the actual change for resolving #107 with a different pr for the styling parts

**Comment by paulhennings** [comment]
Closing without pulling.
Need to put on personal hosting and have a second set of eyes test your changes and approve.
Do not "pretty" code. It makes code review impossible.

**Comment by drothschild** [comment]
My apologies on that. I'll make the changes in a new copy. Do you recommend hosting on personal on Github.io?

**Comment by paulhennings** [comment]
Hi, Yes, that is fine. Most of the team uses github.io hosting.

**Pull request closed without merging**
